### ISSUE TITLE
Won’t login bitstamp

### ISSUE THREAD

**Issue by RED29** [shobrook/BitVision#235]
I filled everything (usercode, key and secret) and it still wont log in. 

Question:
After you start bitvision you get immediately all the stats/charts? Or is that after you after login? 

I ask this because maybe the terminal/npm wont allow connection at all.

**Comment by alichtman** [comment]
> After you start bitvision you get immediately all the stats/charts? 

Yep, the dashboard should immediately populate. No need to login.

**Comment by RED29** [comment]
That means that there is no connection to bitstamp at all. How can I check if the API is correct? I installed it from npm (not building it from source).

**Comment by sh4d0v1** [comment]
Your error might be the same like this one:
https://github.com/shobrook/BitVision/issues/230

**Comment by RED29** [comment]
Its indeed the same one as #230

**Comment by alichtman** [comment]
> How can I check if the API is correct?

@RED29, what do you mean?

**Comment by RED29** [comment]
@alichtman Its not important anymore, I thought the endpoints are not correct, but as far I can see in the retriever.py is correct.

**Comment by alichtman** [comment]
Yeah, the endpoints are definitely correct. One possibility is that the API Keys are getting rate limited because we scaled from 2 developers to however many people are using it now, so maybe the solution is to have people generate their own API keys?

**Comment by RED29** [comment]
Maybe it's not a bad idea. The problem is that there is no good log.

**Comment by shobrook** [comment]
We just pushed a patch that may have fixed this. Could you try upgrading to v1.1.7 and let us know if it works? Thanks.

**Comment by RED29** [comment]
The bug of loading the chart and the global news is all solved! Thanks!

But when I try to log it still gives me an error. The keys are double checked and they are correct.
When I fill in the codes there is always an error always the same error.
When I look in the config.json I see that the codes are in the file but the first line:

**{"logged_in": false,** 

value logged_in is **false.**

Changing this into "**true**" doesn't make any difference, I still can't trade.


Also for MAC OS the terminal need security permission when enabling autotrade, why is that? See attachment.

<img width="670" alt="a1" src="https://user-images.githubusercontent.com/11861774/51416793-54413e00-1b7b-11e9-82d1-2b14a53af3aa.png">

**Comment by shobrook** [comment]
When you try logging in, does a modal saying "Error: Check your connection or credentials" pop up? If it does, then Bitstamp isn't recognizing your credentials. If it doesn't, then it's an issue with either how the Python script for authentication is getting executed, or how the authentication request is being sent, and I'll have to look into this some more.

>Also for MAC OS the terminal need security permission when enabling autotrade, why is that?

When autotrading is enabled, a cron job is scheduled on your computer that will execute a trade every 24hrs. To do this, the terminal needs certain permissions.

**Comment by sh4d0v1** [comment]
>When you try logging in, does a modal saying "Error: Check your connection or credentials" pop up? If it does, then Bitstamp isn't recognizing your credentials

I can't login to BitStamp either: typed and checked API key and secret several times. Assuming "username" is the BitStamp customer ID, which works as username at web login.

Also when copy and pasting the API strings into the config.json (and setting the logged_in flag to true) I am still not logged in, all portfolio stats are zero and pressing "l" gives me a new empty login popup.

Any idea what could prohibit a successful login here?

**Comment by AMerkuri** [comment]
I get "Error: Check your connection or credentials". Account is activated in Bitstamp. Copy-pasted to login modal. I've double checked account credentials, even created new API access user.

**Comment by hgouveia** [comment]
one of the issues is that `services/trader.py` is missing a function called `_default_data` in the parent class BaseClient, that is been called from here https://github.com/shobrook/BitVision/blob/master/services/trader.py#L187

The original code you can see that is declared
https://github.com/kmadac/bitstamp-python-client/blob/master/bitstamp/client.py#L50

for now copying that to the trader.py , fix that issue, but still iam unabled to login

i didnt check any further, but if somebody could continue and probably make a PR

**Comment by chrkaatz** [comment]
+1

**Comment by hgouveia** [comment]
> one of the issues is that `services/trader.py` is missing a function called `_default_data` in the parent class BaseClient, that is been called from here https://github.com/shobrook/BitVision/blob/master/services/trader.py#L187
> 
> The original code you can see that is declared
> https://github.com/kmadac/bitstamp-python-client/blob/master/bitstamp/client.py#L50
> 
> for now copying that to the trader.py , fix that issue, but still iam unabled to login
> 
> i didnt check any further, but if somebody could continue and probably make a PR

i also found that another definition is missing , in the `BaseClient._post`, is missing call to `_default_data`
https://github.com/shobrook/BitVision/blob/master/services/trader.py#L96

here is the missing definition 

https://github.com/kmadac/bitstamp-python-client/blob/master/bitstamp/client.py#L45

**Comment by alichtman** [comment]
> i've also found that , those definition were removed part of this commit: ca789bc

I think you're probably right. I'd guess it's [this method call](https://github.com/shobrook/BitVision/blob/1f987f2dd84f1cdc044f839152243281a1001840/services/trader.py#L187) that's breaking things.

I'd try re-adding the `_default_data()` method in the `BaseClient` class to see if that fixes the problem.

**Comment by shobrook** [comment]
Update to v1.1.9. This should be fixed now.
